name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: List and Read file
          run: |
            echo "my first github actions job"
            ls -ltra
            cat README.md

        - name: Geberate ASCII Artwork
          run: cowsay -f dragon "Run for cover, Iam a Dragon...RAWR" >> dragon.txt
        
        # - name: list files
        #  run: ls

        # name: read file
        #  run: cat README.md